## Pandas层次化索引

In [50]:
import numpy as np
import pandas as pd

### 1. 创建多层行索引

#### 1) 隐式构造

最常见的方法是给DataFrame构造函数的index参数传递两个或更多的数组

In [51]:
data = np.random.randint(0, 100, size=(6, 6))

index = [
    ['1班',  '1班',   '1班',  '2班', '2班', '2班'],
    ['张三', '李四', '王五', '鲁班', '张三丰', '张无忌']
]
columns = [
    ['期中', '期中', '期中', '期末', '期末', '期末'],
    ['语文', '数学', '英语', '语文', '数学', '英语']
]

df = pd.DataFrame(data=data, index=index, columns=columns)
df

        期中          期末
        语文  数学  英语  语文  数学  英语
1班 张三   27  35   8  69  95  30
   李四   34  60  86  83  22  11
   王五   94  24  98  50  71  97
2班 鲁班   71  36  28  48  80  46
   张三丰  35  48  54   9   1   9
   张无忌  52  37  35  65   6   7

- Series也可以创建多层索引

In [52]:
data = np.random.randint(0, 100, size=6)

index = [
    ['1班',  '1班',   '1班',  '2班', '2班', '2班'],
    ['张三', '李四', '王五', '鲁班', '张三丰', '张无忌']
]

s = pd.Series(data=data, index=index)
s

1班  张三     34
    李四     65
    王五     60
2班  鲁班     49
    张三丰    20
    张无忌    27
dtype: int32

#### 2) 显示构造pd.MultiIndex

- 使用数组

In [53]:
data = np.random.randint(0, 100, size=(6, 6))

index = pd.MultiIndex.from_arrays( [
    ['1班',  '1班',   '1班',  '2班', '2班', '2班'],
    ['张三', '李四', '王五', '鲁班', '张三丰', '张无忌']
])
columns = [
    ['期中', '期中', '期中', '期末', '期末', '期末'],
    ['语文', '数学', '英语', '语文', '数学', '英语']
]

df = pd.DataFrame(data=data, index=index, columns=columns)
df

        期中          期末
        语文  数学  英语  语文  数学  英语
1班 张三    5  30   4  32   8   1
   李四   75   0  86  34  26  69
   王五   50  73  33  41  98  10
2班 鲁班   29  63  14  23  48  65
   张三丰  27   2  43  40  35  45
   张无忌  50  28  11  38  55  37

- 使用tuple

In [54]:
data = np.random.randint(0, 100, size=(6, 6))

index = pd.MultiIndex.from_tuples(
    (
        ('1班', '张三'), ('1班', '李四'), ('1班', '王五'),
        ('2班', '鲁班'), ('2班', '张三丰'), ('2班', '张无忌')
    )
)

columns = [
    ['期中', '期中', '期中', '期末', '期末', '期末'],
    ['语文', '数学', '英语', '语文', '数学', '英语']
]

df = pd.DataFrame(data=data, index=index, columns=columns)
df

        期中          期末
        语文  数学  英语  语文  数学  英语
1班 张三   81  45  86  70  10   2
   李四   57  67  36  10  18   2
   王五   26  49  41  39  20  60
2班 鲁班   66  46  78   5  87  25
   张三丰  62  10  32  27  97  11
   张无忌  28  60  23  46  37  66

- 使用product
    - 笛卡尔积

In [55]:
data = np.random.randint(0, 100, size=(6, 6))

# 笛卡尔积: {a, b} {c, d} => {a, c}, {a, d}, {b, c}, {b, d}

index = pd.MultiIndex.from_product( [
    ['1班',  '2班'],
    ['张三', '李四', '王五']
])
columns = [
    ['期中', '期中', '期中', '期末', '期末', '期末'],
    ['语文', '数学', '英语', '语文', '数学', '英语']
]

df = pd.DataFrame(data=data, index=index, columns=columns)
df

       期中          期末
       语文  数学  英语  语文  数学  英语
1班 张三  82  15  48  35  24  50
   李四  50  75  19  75  72  10
   王五  66  99  27  74  16  72
2班 张三  20  30  35  21  54  22
   李四  93  65  11   3  44  11
   王五  31   7  85  31  69  55

### 2. 多层列索引

除了行索引index，列索引columns也能用同样的方法创建多层索引

### 3. 多层索引对象的索引与切片操作

#### 1）Series的操作

- 对于Series来说，直接中括号[]与使用.loc()完全一样

(1) 索引

In [56]:
s

1班  张三     34
    李四     65
    王五     60
2班  鲁班     49
    张三丰    20
    张无忌    27
dtype: int32

In [57]:
# 显式索引
s['1班']
s.loc['1班']

s[['1班']]
s[['1班', '2班']]

s['1班']['张三']
s.loc['1班']['张三']
s.loc['1班', '张三']
s['1班', '张三']

# 隐式索引
s[0]
s[1]
s.iloc[1]
s.iloc[[1, 2]]

C:\Users\Administrator\AppData\Local\Temp\ipykernel_26104\524077654.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[0]
C:\Users\Administrator\AppData\Local\Temp\ipykernel_26104\524077654.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[1]

1班  李四    65
    王五    60
dtype: int32

(2) 切片

In [58]:
s

1班  张三     34
    李四     65
    王五     60
2班  鲁班     49
    张三丰    20
    张无忌    27
dtype: int32

In [59]:
# 切片
# 显式切片
s['1班' : '2班']
s.loc['1班' : '2班']
s.loc['1班'][:]

# 建议使用隐式索引
s[1 : 5]
s.iloc[1 : 5]

1班  李四     65
    王五     60
2班  鲁班     49
    张三丰    20
dtype: int32

#### 2）DataFrame的操作

(1) 索引

In [60]:
df

       期中          期末
       语文  数学  英语  语文  数学  英语
1班 张三  82  15  48  35  24  50
   李四  50  75  19  75  72  10
   王五  66  99  27  74  16  72
2班 张三  20  30  35  21  54  22
   李四  93  65  11   3  44  11
   王五  31   7  85  31  69  55

In [61]:
# 列索引
df['期中']
df['期中'][['数学']]
df['期中']['数学']
df['期中', '数学']
df.期中.数学

df.iloc[:, 2]
df.iloc[:, [0, 2, 1]]
df.loc[:, ('期中', '数学')]

# # 行索引
df.loc['2班']
df.loc['2班'].loc['张三']
df.loc['2班', '张三']
df.loc[('2班', '张三')]

df.iloc[1]
df.iloc[[1]]
df.iloc[[1, 3, 4, 2]]

       期中          期末
       语文  数学  英语  语文  数学  英语
1班 李四  50  75  19  75  72  10
2班 张三  20  30  35  21  54  22
   李四  93  65  11   3  44  11
1班 王五  66  99  27  74  16  72

In [62]:
# 获取元素
df['期中']['数学']['1班']['张三']
df['期中']['数学']['1班'][0]

df.iloc[0, 1]
df.loc[('1班', '张三'), ('期中', '数学')]

C:\Users\Administrator\AppData\Local\Temp\ipykernel_26104\1751359348.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['期中']['数学']['1班'][0]

np.int32(15)

(2) 切片

In [63]:
df

       期中          期末
       语文  数学  英语  语文  数学  英语
1班 张三  82  15  48  35  24  50
   李四  50  75  19  75  72  10
   王五  66  99  27  74  16  72
2班 张三  20  30  35  21  54  22
   李四  93  65  11   3  44  11
   王五  31   7  85  31  69  55

In [64]:
# 行切片
df.iloc[1 : 5]
df.loc[('1班', '李四') : ('2班', '李四')]
df.loc['1班' : '2班']

# 列切片
df.iloc[:, 1: 5]
df.loc[:, '期中': '期末']
# df.loc[:, ('期中', '数学') : ('期末', '数学')]  # 报错

# 建议切片使用隐式索引：
#    使用数字下标来做偏

       期中          期末
       语文  数学  英语  语文  数学  英语
1班 张三  82  15  48  35  24  50
   李四  50  75  19  75  72  10
   王五  66  99  27  74  16  72
2班 张三  20  30  35  21  54  22
   李四  93  65  11   3  44  11
   王五  31   7  85  31  69  55

### 4. 索引的堆叠

- stack()
- unstack()

【小技巧】使用stack()的时候，level等于哪一个，哪一个就消失，出现在行里。

In [65]:
data = np.random.randint(0, 100, size=(6, 6))

# 笛卡尔积: {a, b} {c, d} => {a, c}, {a, d}, {b, c}, {b, d}

index = pd.MultiIndex.from_product( [
    ['1班',  '2班'],
    ['张三', '李四', '王五']
])
columns = [
    ['期中', '期中', '期中', '期末', '期末', '期末'],
    ['语文', '数学', '英语', '语文', '数学', '英语']
]

df = pd.DataFrame(data=data, index=index, columns=columns)
df

       期中          期末
       语文  数学  英语  语文  数学  英语
1班 张三  50  73  43   4  87  80
   李四  28  17  88  64  37  65
   王五  90  62  60  90  52  93
2班 张三  19   3  89  45  85  81
   李四  16  58  45  73  91  52
   王五  54  42  76  90  43  48

In [66]:
# stack: 将列索引变成行索引
df.stack()   # 默认是将最里层的列索引变成行索引
df.stack(level=-1)
df.stack(level=1)

df2 = df.stack(level=0)
df2

C:\Users\Administrator\AppData\Local\Temp\ipykernel_26104\3034055741.py:2: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df.stack()   # 默认是将最里层的列索引变成行索引
C:\Users\Administrator\AppData\Local\Temp\ipykernel_26104\3034055741.py:3: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df.stack(level=-1)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_26104\3034055741.py:4: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df.stack(level=1)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_26104\3034055741.py:6: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df2 = df.stack(level=0)

          语文  数学  英语
1班 张三 期中  50  73  43
      期末   4  87  80
   李四 期中  28  17  88
      期末  64  37  65
   王五 期中  90  62  60
      期末  90  52  93
2班 张三 期中  19   3  89
      期末  45  85  81
   李四 期中  16  58  45
      期末  73  91  52
   王五 期中  54  42  76
      期末  90  43  48

【小技巧】使用unstack()的时候，level等于哪一个，哪一个就消失，出现在列里。

In [67]:
# unstack: 将行索引变成列索引
df2.unstack()
df2.unstack(level=-1)
df2.unstack(level=2)
df2.unstack(level=1)
df2.unstack(level=0)

       语文      数学      英语
       1班  2班  1班  2班  1班  2班
张三 期中  50  19  73   3  43  89
   期末   4  45  87  85  80  81
李四 期中  28  16  17  58  88  45
   期末  64  73  37  91  65  52
王五 期中  90  54  62  42  60  76
   期末  90  90  52  43  93  48

使用fill_value填充

In [68]:
data = np.random.randint(0, 100, size=(6, 6))

index = pd.MultiIndex.from_tuples(
    (
        ('1班', '张三'), ('1班', '李四'), ('1班', '王五'),
        ('2班', '鲁班'), ('2班', '张三丰'), ('2班', '张无忌')
    )
)

columns = [
    ['期中', '期中', '期中', '期末', '期末', '期末'],
    ['语文', '数学', '英语', '语文', '数学', '英语']
]

df = pd.DataFrame(data=data, index=index, columns=columns)
df

        期中          期末
        语文  数学  英语  语文  数学  英语
1班 张三   56  56  58  28   3  17
   李四   67  76  33  86  54  65
   王五   53  17  43  31  14  66
2班 鲁班   68  56  95  78  16  48
   张三丰  21  17  77  42  67  83
   张无忌  55  23  42  30  10  22

In [69]:
df.unstack()

df.unstack(fill_value=0)

    期中                                      ...  期末                          \
    语文                      数学              ...  数学              英语
    张三 张三丰 张无忌  李四  王五  鲁班  张三 张三丰 张无忌  李四  ... 张无忌  李四  王五  鲁班  张三 张三丰 张无忌
1班  56   0   0  67  53   0  56   0   0  76  ...   0  54  14   0  17   0   0
2班   0  21  55   0   0  68   0  17  23   0  ...  10   0   0  16   0  83  22



    李四  王五  鲁班
1班  65  66   0
2班   0   0  48

[2 rows x 36 columns]

### 5. 聚合操作

DataFrame聚合函数
- 求和
- 平均值
- 最大值
- 最小值等

In [70]:
df

        期中          期末
        语文  数学  英语  语文  数学  英语
1班 张三   56  56  58  28   3  17
   李四   67  76  33  86  54  65
   王五   53  17  43  31  14  66
2班 鲁班   68  56  95  78  16  48
   张三丰  21  17  77  42  67  83
   张无忌  55  23  42  30  10  22

In [71]:
df2 = df.loc['1班',  '期中']
df2

    语文  数学  英语
张三  56  56  58
李四  67  76  33
王五  53  17  43

In [72]:
df2.values.sum()

np.int64(459)

In [73]:
df2.sum()
df2.sum(axis=0)  # 求每一列中多行的和
df2.sum(axis=1)  # 求每一行中多列的和

张三    170
李四    176
王五    113
dtype: int64

In [74]:
df2.mean()
df2.max()

语文    67
数学    76
英语    58
dtype: int32

多层索引聚合操作

In [75]:
df

        期中          期末
        语文  数学  英语  语文  数学  英语
1班 张三   56  56  58  28   3  17
   李四   67  76  33  86  54  65
   王五   53  17  43  31  14  66
2班 鲁班   68  56  95  78  16  48
   张三丰  21  17  77  42  67  83
   张无忌  55  23  42  30  10  22

In [76]:
df.sum()  # 默认是求每一列中多行的和
df.sum(axis=0)

期中  语文    320
    数学    245
    英语    348
期末  语文    295
    数学    164
    英语    301
dtype: int64

In [77]:
df.sum(axis=1)  # 默认是求每一行中多列的和

1班  张三     218
    李四     381
    王五     224
2班  鲁班     361
    张三丰    307
    张无忌    182
dtype: int64

In [78]:
df.sum(axis=0, level=0)  # 表式计算 行 中 的第1层（level=0）
df.sum(axis=0, level=1)  # 表式计算 行 中 的第2层（level=1）

df.sum(axis=1, level=0)  # 表式计算 列 中 的第1层（level=0）
df.sum(axis=1, level=1)  # 表式计算 列 中 的第2层（level=1）

TypeError: sum() got an unexpected keyword argument 'level'