### Pandas数学函数

In [1]:
import numpy as np
import pandas as pd

- 聚合函数

In [2]:
df = pd.DataFrame(data=np.random.randint(0, 100, size=(5, 3)))
df

    0   1   2
0  36  62  98
1  20  72  89
2  79  64   3
3  12  43   5
4  89  15   8

In [3]:
df.count()  # 非空的数量
df.count(axis=1)

df.max()  # 默认求在每一列中不同行之间的最大值
df.max(axis=1)

df.min()  # 最小值
df.min(axis=1)

df.median()  # 中位数

df.sum()  # 求和
# df.values.sum()  # 求所有元素的和
df.sum(axis=1)

df.mean() # 平均值
df.mean(axis=1)

0    65.333333
1    60.333333
2    48.666667
3    20.000000
4    37.333333
dtype: float64

- 方差: 
    - 当数据分布比较分散（即数据在平均数附近波动较大）时，各个数据与平均数的差的平方和较大，方差就较大；
    - 当数据分布比较集中时，各个数据与平均数的差的平方和较小。
    - 因此方差越大，数据的波动越大；方差越小数据的波动就越小
- 标准差
    - 标准差 = 方差的算术平方根

In [4]:
df

    0   1   2
0  36  62  98
1  20  72  89
2  79  64   3
3  12  43   5
4  89  15   8

In [5]:
df.var()  # 方差

0    1215.7
1     522.7
2    2345.3
dtype: float64

In [6]:
df.std()  # 标准差

0    34.866890
1    22.862633
2    48.428298
dtype: float64

- 其他数学函数

In [7]:
df

    0   1   2
0  36  62  98
1  20  72  89
2  79  64   3
3  12  43   5
4  89  15   8

In [8]:
df[1].value_counts()  # 统计元素出现次数

1
62    1
72    1
64    1
43    1
15    1
Name: count, dtype: int64

In [9]:
df.cumsum()  # 累加

     0    1    2
0   36   62   98
1   56  134  187
2  135  198  190
3  147  241  195
4  236  256  203

In [10]:
df.cumprod()  # 累乘

          0          1        2
0        36         62       98
1       720       4464     8722
2     56880     285696    26166
3    682560   12284928   130830
4  60747840  184273920  1046640

- 协方差
    - 两组数值中每对变量的偏差乘积的平均值    
    - 协方差>0 : 表式两组变量正相关
         - 如果两个变量的变化趋势一致，也就是说如果其中一个大于自身的期望值时另外一个也大于自身的期望值，那么两个变量之间的协方差就是正值；
    - 协方差<0 : 表式两组变量负相关
        - 如果两个变量的变化趋势相反，即其中一个变量大于自身的期望值时另外一个却小于自身的期望值，那么两个变量之间的协方差就是负值。
    - 协方差=0 : 表式两组变量不相关

In [11]:
df.cov()  # 协方差
df[0].cov(df[1])   # 第0列和第1列的协方差

np.float64(-376.05)

- 相关系数r
    - 相关系数 = X与Y的协方差 / (X的标准差 * Y的标准差)
    - 相关系数值的范围在-1和+1之间
    - r＞0为正相关，r＜0为负相关。r＝0表示不相关
    - r 的绝对值越大，相关程度越高

In [12]:
df.corr()  # 所有特征相关系数
df.corrwith(df[2])  # 单一特征相关系数

0   -0.483345
1    0.590996
2    1.000000
dtype: float64