## Pandas加载数据

In [1]:
import numpy as np
import pandas as pd

### csv数据

In [2]:
data = np.random.randint(0, 50, size=(10, 5))
df = pd.DataFrame(data=data, columns=['Python', 'Qianfeng', 'Java', 'NumPy', 'Pandas'])
df

   Python  Qianfeng  Java  NumPy  Pandas
0      13        43    32     34      35
1      31        27     3     37      29
2      10        43    40     15      48
3      48        39     4     43      40
4      36        10    34      5      28
5      16        10    23     42       9
6      29         4    12      0      45
7      21        20    30     47      21
8      13        25    29     38       2
9      45         9     5     33      22

- df.to_csv: 保存到csv

In [3]:
# sep: 分隔符，默认是逗号
# header: 是否保存列索引
# index: 是否保留行索引
df.to_csv('data.csv', sep=',', header=True, index=True)

- df.read_csv: 加载csv数据

In [4]:
pd.read_csv('data.csv', sep=',', header=[0], index_col=0)

   Python  Qianfeng  Java  NumPy  Pandas
0      13        43    32     34      35
1      31        27     3     37      29
2      10        43    40     15      48
3      48        39     4     43      40
4      36        10    34      5      28
5      16        10    23     42       9
6      29         4    12      0      45
7      21        20    30     47      21
8      13        25    29     38       2
9      45         9     5     33      22

不获取列: header=None

In [5]:
pd.read_csv('data.csv', sep=',', header=None, index_col=0)

          1         2     3      4       5
0
NaN  Python  Qianfeng  Java  NumPy  Pandas
0.0      13        43    32     34      35
1.0      31        27     3     37      29
2.0      10        43    40     15      48
3.0      48        39     4     43      40
4.0      36        10    34      5      28
5.0      16        10    23     42       9
6.0      29         4    12      0      45
7.0      21        20    30     47      21
8.0      13        25    29     38       2
9.0      45         9     5     33      22

- pd.read_table

In [6]:
# read_table :
#    默认分隔符sep='\t'
pd.read_table('data.csv', sep=',', index_col=0)

   Python  Qianfeng  Java  NumPy  Pandas
0      13        43    32     34      35
1      31        27     3     37      29
2      10        43    40     15      48
3      48        39     4     43      40
4      36        10    34      5      28
5      16        10    23     42       9
6      29         4    12      0      45
7      21        20    30     47      21
8      13        25    29     38       2
9      45         9     5     33      22

### excel数据

In [7]:
data = np.random.randint(0, 50, size=(10, 5))
df = pd.DataFrame(data=data, columns=['Python', 'Qianfeng', 'Java', 'NumPy', 'Pandas'])
df

   Python  Qianfeng  Java  NumPy  Pandas
0       3        44    23      9      45
1      26        41     7     31       7
2       3         6     7      1      16
3      40         0    32     16      17
4      10        17    21     22       5
5      17        49    31     20       7
6      19        15    42     48       4
7      32        36    22     44      17
8      38        40     1     13      30
9       2        23    19     38      33

- df1.to_excel: 保存到excel文件

In [8]:
# sheet_name： 工作表名称
# header: 是否保存列索引
# index: 是否保存行索引
df.to_excel('data.xlsx', sheet_name='Sheet1', header=True, index=False)

- df1.read_excel: 读取excel

In [9]:
pd.read_excel('data.xlsx', sheet_name='Sheet1', header=[0, 1])

# sheet_name=0： 读取第1个工作表
# names : 替换原来的列名
pd.read_excel('data.xlsx', sheet_name=0, header=0, names=list('ABCDE'))

    A   B   C   D   E
0   3  44  23   9  45
1  26  41   7  31   7
2   3   6   7   1  16
3  40   0  32  16  17
4  10  17  21  22   5
5  17  49  31  20   7
6  19  15  42  48   4
7  32  36  22  44  17
8  38  40   1  13  30
9   2  23  19  38  33

### MySQL数据

需要安装pymysql

- pip install pymysql -i https://pypi.tuna.tsinghua.edu.cn/simple

In [10]:
pip install pymysql -i https://pypi.tuna.tsinghua.edu.cn/simple

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting pymysql
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/0c/94/e4181a1f6286f545507528c78016e00065ea913276888db2262507693ce5/PyMySQL-1.1.1-py3-none-any.whl (44 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1
Note: you may need to restart the kernel to use updated packages.

需要安装sqlalchemy: 

- pip install sqlalchemy -i https://pypi.tuna.tsinghua.edu.cn/simple
- sqlalchemy是Python语言下的数据库引擎库

In [11]:
pip install sqlalchemy -i https://pypi.tuna.tsinghua.edu.cn/simple

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting sqlalchemy
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/e8/86/989f4b4c47da0d9b152465f6623b6a6415179b4e6bb967f08199bdad98eb/SQLAlchemy-2.0.32-cp310-cp310-win_amd64.whl (2.1 MB)
     ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
     ---------------------------------------- 2.1/2.1 MB 11.7 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4.6.0 in d:\developer\wgj\vscode_workspace\python\pyecharts\.venv\lib\site-packages (from sqlalchemy) (4.12.2)
Collecting greenlet!=0.4.17 (from sqlalchemy)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/a6/76/e1ee9f290bb0d46b09704c2fb0e609cae329eb308ad404c0ee6fa1ecb8a5/greenlet-3.0.3-cp310-cp310-win_amd64.whl (292 kB)
Installing collected packages: greenlet, sqlalchemy
Successfully installed greenlet-3.0.3 sqlalchemy-2.0.32
Note: you may need to restart the kernel to use updated packages.

In [12]:
from sqlalchemy import create_engine

In [13]:
# 创建数据
data = np.random.randint(0, 150, size=(150, 3))
df = pd.DataFrame(data=data, columns=['Python', 'Pandas', 'PyTorch'])
df.head()

   Python  Pandas  PyTorch
0      88      84      101
1      51      24       57
2      51     127       20
3      57      10       68
4       0      28       84

- 先连接MySQL

In [16]:
# mysql+pymysql ：数据库类型+驱动
# root:root ：数据库用户名和密码
# localhost:3306 ：数据库地址和MySQL端口
# db: 数据库名
conn = create_engine('mysql+pymysql://root:123456@localhost:3306/db')

- df.to_sql保存到MySQL

In [17]:
df.to_sql(
    name='score',  # 数据库中表名字
    con=conn,  # 数据库连接对象
    index=False,  # 是否保存行索引
    if_exists='append'  # 如果表存在，则追加数据
)

150

- pd.read_sql: 从MySQL中加载数据

In [18]:
pd.read_sql(
    sql='select * from score',  # sql语句
    con=conn,   # 数据库连接对象
#     index_col='Python'  # 指定行索引的列名
)

     Python  Pandas  PyTorch
0        88      84      101
1        51      24       57
2        51     127       20
3        57      10       68
4         0      28       84
..      ...     ...      ...
145      59      91       82
146     114      42       51
147     115     108      140
148       5      46       34
149     141      84       71

[150 rows x 3 columns]