### Pandas时间序列

In [2]:
import numpy as np
import pandas as pd

#### 时间戳

In [3]:
# 1.创建
pd.Timestamp('2023-01-01')
pd.Period('2023-01-01',freq='D')
# freq:Y:年 M:月 D:日

# 批量生成时刻数据
# periods=4 创建4个时间
index = pd.date_range('2030.02.13',periods=4,freq='D') # 时刻数据
# index = pd.period_range('2030.02.13',periods=4,freq='D') # 时期数据
index

# 时间戳索引
pd.Series(np.random.randint(0, 10, size=4),index=index)

2030-02-13    3
2030-02-14    2
2030-02-15    6
2030-02-16    8
Freq: D, dtype: int32

In [4]:
# 2.转换方法
# pd.to_datetime(['2030.03.14', '2030-03-14', '14/03/2030', '2030/3/14'])

# 时间戳->时间
pd.to_datetime([1899678987], unit='s')

dt = pd.to_datetime([1899678987], unit='ms')
display(dt)

# 时间差 DateOffset
dt + pd.DateOffset(hours=8) # +8小时
dt + pd.DateOffset(days=8) # +8天
dt + pd.DateOffset(days=-8) #-8天

DatetimeIndex(['1970-01-22 23:41:18.987000'], dtype='datetime64[ns]', freq=None)

DatetimeIndex(['1970-01-14 23:41:18.987000'], dtype='datetime64[ns]', freq=None)

In [5]:
# 3.时间戳的索引和切片
index = pd.date_range('2030-3-14', periods=100, freq='D')
index

ts = pd.Series(range(len(index)), index=index)
ts

2030-03-14     0
2030-03-15     1
2030-03-16     2
2030-03-17     3
2030-03-18     4
              ..
2030-06-17    95
2030-06-18    96
2030-06-19    97
2030-06-20    98
2030-06-21    99
Freq: D, Length: 100, dtype: int64

In [6]:
# 索引
ts['2030-03-15'] # 索引
ts['2030-03'] # 3月份
ts['2030'] # 2030年

ts['2030-03-15':'2030-03-20'] # 2030年3月15日到20日

2030-03-15    1
2030-03-16    2
2030-03-17    3
2030-03-18    4
2030-03-19    5
2030-03-20    6
Freq: D, dtype: int64

In [7]:
# 时间戳索引
pd.Timestamp('2030-3-22')
ts[pd.Timestamp('2030-3-22')]

# 切片
ts[pd.Timestamp('2030-3-15'):pd.Timestamp('2030-3-22')]

# date_range
ts[pd.date_range('2030-3-24',periods=10, freq='D')]

2030-03-24    10
2030-03-25    11
2030-03-26    12
2030-03-27    13
2030-03-28    14
2030-03-29    15
2030-03-30    16
2030-03-31    17
2030-04-01    18
2030-04-02    19
Freq: D, dtype: int64

In [8]:
# 4.属性
ts.index

ts.index.year
ts.index.month
ts.index.day
ts.index.dayofweek

Index([3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5,
       6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1,
       2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4,
       5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0,
       1, 2, 3, 4],
      dtype='int32')

#### 时间序列常用方法
- 对时间做一些移动/滞后、频率转换、采样等操作

In [11]:
index = pd.date_range('2030-3-1', periods=365, freq='D')
ts = pd.Series(np.random.randint(0, 500, len(index)), index=index)
ts

2030-03-01     23
2030-03-02    404
2030-03-03    362
2030-03-04    365
2030-03-05    405
             ...
2031-02-24    267
2031-02-25    440
2031-02-26     12
2031-02-27    170
2031-02-28    189
Freq: D, Length: 365, dtype: int32

In [14]:
# 1.移动
ts.shift() # 向后移动1天
ts.shift(periods=2) # 向后移动2位

2030-03-01      NaN
2030-03-02      NaN
2030-03-03     23.0
2030-03-04    404.0
2030-03-05    362.0
              ...
2031-02-24    320.0
2031-02-25    347.0
2031-02-26    267.0
2031-02-27    440.0
2031-02-28     12.0
Freq: D, Length: 365, dtype: float64

In [20]:
# 2.频率转换
ts.asfreq(pd.tseries.offsets.Week()) # 天 -> 周
ts.asfreq(pd.tseries.offsets.MonthEnd()) # 天 -> 月

# 由少变多 fill_value 填充
ts.asfreq(pd.tseries.offsets.Hour(), fill_value=0) # 天 -> 小时

2030-03-01 00:00:00     23
2030-03-01 01:00:00      0
2030-03-01 02:00:00      0
2030-03-01 03:00:00      0
2030-03-01 04:00:00      0
                      ...
2031-02-27 20:00:00      0
2031-02-27 21:00:00      0
2031-02-27 22:00:00      0
2031-02-27 23:00:00      0
2031-02-28 00:00:00    189
Freq: h, Length: 8737, dtype: int32

#### resample:根据日期维度进行数据聚合
- 按照分钟(T)、小时(H)、日(D)、周(W)、月(M)、年(Y)等作为日期维度

In [21]:
ts

2030-03-01     23
2030-03-02    404
2030-03-03    362
2030-03-04    365
2030-03-05    405
             ...
2031-02-24    267
2031-02-25    440
2031-02-26     12
2031-02-27    170
2031-02-28    189
Freq: D, Length: 365, dtype: int32

In [33]:
# 3.重采样
ts.resample('2D').sum() # 按天聚合求和
ts.resample('2W').sum() # 按2个星期为单位进行汇总，求和
ts.resample('3ME').sum() # 按3个月为单位进行汇总，求和
ts.resample('3ME').sum().cumsum() # 按3个月为单位进行汇总，求和，并累加

ts.resample('h').sum()
ts.resample('min').sum()
ts.resample('s').sum()

2030-03-01 00:00:00     23
2030-03-01 00:00:01      0
2030-03-01 00:00:02      0
2030-03-01 00:00:03      0
2030-03-01 00:00:04      0
                      ...
2031-02-27 23:59:56      0
2031-02-27 23:59:57      0
2031-02-27 23:59:58      0
2031-02-27 23:59:59      0
2031-02-28 00:00:00    189
Freq: s, Length: 31449601, dtype: int32

In [34]:
# 4.DataFrame重采样
d = {
    'price': [10, 11, 2, 44, 33, 44, 55, 66],
    'score': [40, 30, 20, 50, 60, 70, 80, 10],
    'week': pd.date_range('2030-3-1', periods=8, freq='W')
}

df = pd.DataFrame(d)
df

   price  score       week
0     10     40 2030-03-03
1     11     30 2030-03-10
2      2     20 2030-03-17
3     44     50 2030-03-24
4     33     60 2030-03-31
5     44     70 2030-04-07
6     55     80 2030-04-14
7     66     10 2030-04-21

In [43]:
# 对week列进行按月汇总求和
df.resample('ME', on='week').sum()
df.resample('ME', on='week').apply(lambda x: x.sum())

# 对week列进行按月汇总求和 ，并计算平均价格 和总分数
df.resample('ME', on='week').agg({'price': 'mean', 'score': 'sum'})

            price  score
week
2030-03-31   20.0    200
2030-04-30   55.0    160

#### 时区

In [51]:
index = pd.date_range('2030-3-1', periods=3, freq='D')
ts = pd.Series(np.random.randn(len(index)), index=index)
ts

2030-03-01   -1.565496
2030-03-02   -0.526696
2030-03-03    1.001550
Freq: D, dtype: float64

In [47]:
# tz: timezone
import pytz

In [48]:
pytz.common_timezones

['Africa/Abidjan', 'Africa/Accra', 'Africa/Addis_Ababa', 'Africa/Algiers', 'Africa/Asmara', 'Africa/Bamako', 'Africa/Bangui', 'Africa/Banjul', 'Africa/Bissau', 'Africa/Blantyre', 'Africa/Brazzaville', 'Africa/Bujumbura', 'Africa/Cairo', 'Africa/Casablanca', 'Africa/Ceuta', 'Africa/Conakry', 'Africa/Dakar', 'Africa/Dar_es_Salaam', 'Africa/Djibouti', 'Africa/Douala', 'Africa/El_Aaiun', 'Africa/Freetown', 'Africa/Gaborone', 'Africa/Harare', 'Africa/Johannesburg', 'Africa/Juba', 'Africa/Kampala', 'Africa/Khartoum', 'Africa/Kigali', 'Africa/Kinshasa', 'Africa/Lagos', 'Africa/Libreville', 'Africa/Lome', 'Africa/Luanda', 'Africa/Lubumbashi', 'Africa/Lusaka', 'Africa/Malabo', 'Africa/Maputo', 'Africa/Maseru', 'Africa/Mbabane', 'Africa/Mogadishu', 'Africa/Monrovia', 'Africa/Nairobi', 'Africa/Ndjamena', 'Africa/Niamey', 'Africa/Nouakchott', 'Africa/Ouagadougou', 'Africa/Porto-Novo', 'Africa/Sao_Tome', 'Africa/Tripoli', 'Africa/Tunis', 'Africa/Windhoek', 'America/Adak', 'America/Anchorage', 'America/Anguilla', 'America/Antigua', 'America/Araguaina', 'America/Argentina/Buenos_Aires', 'America/Argentina/Catamarca', 'America/Argentina/Cordoba', 'America/Argentina/Jujuy', 'America/Argentina/La_Rioja', 'America/Argentina/Mendoza', 'America/Argentina/Rio_Gallegos', 'America/Argentina/Salta', 'America/Argentina/San_Juan', 'America/Argentina/San_Luis', 'America/Argentina/Tucuman', 'America/Argentina/Ushuaia', 'America/Aruba', 'America/Asuncion', 'America/Atikokan', 'America/Bahia', 'America/Bahia_Banderas', 'America/Barbados', 'America/Belem', 'America/Belize', 'America/Blanc-Sablon', 'America/Boa_Vista', 'America/Bogota', 'America/Boise', 'America/Cambridge_Bay', 'America/Campo_Grande', 'America/Cancun', 'America/Caracas', 'America/Cayenne', 'America/Cayman', 'America/Chicago', 'America/Chihuahua', 'America/Ciudad_Juarez', 'America/Costa_Rica', 'America/Creston', 'America/Cuiaba', 'America/Curacao', 'America/Danmarkshavn', 'America/Dawson', 'America/Dawson_Creek', 'America/Denver', 'America/Detroit', 'America/Dominica', 'America/Edmonton', 'America/Eirunepe', 'America/El_Salvador', 'America/Fort_Nelson', 'America/Fortaleza', 'America/Glace_Bay', 'America/Goose_Bay', 'America/Grand_Turk', 'America/Grenada', 'America/Guadeloupe', 'America/Guatemala', 'America/Guayaquil', 'America/Guyana', 'America/Halifax', 'America/Havana', 'America/Hermosillo', 'America/Indiana/Indianapolis', 'America/Indiana/Knox', 'America/Indiana/Marengo', 'America/Indiana/Petersburg', 'America/Indiana/Tell_City', 'America/Indiana/Vevay', 'America/Indiana/Vincennes', 'America/Indiana/Winamac', 'America/Inuvik', 'America/Iqaluit', 'America/Jamaica', 'America/Juneau', 'America/Kentucky/Louisville', 'America/Kentucky/Monticello', 'America/Kralendijk', 'America/La_Paz', 'America/Lima', 'America/Los_Angeles', 'America/Lower_Princes', 'America/Maceio', 'America/Managua', 'America/Manaus', 'America/Marigot', 'America/Martinique', 'America/Matamoros', 'America/Mazatlan', 'America/Menominee', 'America/Merida', 'America/Metlakatla', 'America/Mexico_City', 'America/Miquelon', 'America/Moncton', 'America/Monterrey', 'America/Montevideo', 'America/Montserrat', 'America/Nassau', 'America/New_York', 'America/Nome', 'America/Noronha', 'America/North_Dakota/Beulah', 'America/North_Dakota/Center', 'America/North_Dakota/New_Salem', 'America/Nuuk', 'America/Ojinaga', 'America/Panama', 'America/Paramaribo', 'America/Phoenix', 'America/Port-au-Prince', 'America/Port_of_Spain', 'America/Porto_Velho', 'America/Puerto_Rico', 'America/Punta_Arenas', 'America/Rankin_Inlet', 'America/Recife', 'America/Regina', 'America/Resolute', 'America/Rio_Branco', 'America/Santarem', 'America/Santiago', 'America/Santo_Domingo', 'America/Sao_Paulo', 'America/Scoresbysund', 'America/Sitka', 'America/St_Barthelemy', 'America/St_Johns', 'America/St_Kitts', 'America/St_Lucia', 'America/St_Thomas', 'America/St_Vincent', 'America/Swift_Current', 'America/Tegucigalpa', 'America/Thule', 'America/Tijuana', 'America/Toronto', 'America/Tortola', 'America/Vancouver', 'America/Whitehorse', 'America/Winnipeg', 'America/Yakutat', 'Antarctica/Casey', 'Antarctica/Davis', 'Antarctica/DumontDUrville', 'Antarctica/Macquarie', 'Antarctica/Mawson', 'Antarctica/McMurdo', 'Antarctica/Palmer', 'Antarctica/Rothera', 'Antarctica/Syowa', 'Antarctica/Troll', 'Antarctica/Vostok', 'Arctic/Longyearbyen', 'Asia/Aden', 'Asia/Almaty', 'Asia/Amman', 'Asia/Anadyr', 'Asia/Aqtau', 'Asia/Aqtobe', 'Asia/Ashgabat', 'Asia/Atyrau', 'Asia/Baghdad', 'Asia/Bahrain', 'Asia/Baku', 'Asia/Bangkok', 'Asia/Barnaul', 'Asia/Beirut', 'Asia/Bishkek', 'Asia/Brunei', 'Asia/Chita', 'Asia/Choibalsan', 'Asia/Colombo', 'Asia/Damascus', 'Asia/Dhaka', 'Asia/Dili', 'Asia/Dubai', 'Asia/Dushanbe', 'Asia/Famagusta', 'Asia/Gaza', 'Asia/Hebron', 'Asia/Ho_Chi_Minh', 'Asia/Hong_Kong', 'Asia/Hovd', 'Asia/Irkutsk', 'Asia/Jakarta', 'Asia/Jayapura', 'Asia/Jerusalem', 'Asia/Kabul', 'Asia/Kamchatka', 'Asia/Karachi', 'Asia/Kathmandu', 'Asia/Khandyga', 'Asia/Kolkata', 'Asia/Krasnoyarsk', 'Asia/Kuala_Lumpur', 'Asia/Kuching', 'Asia/Kuwait', 'Asia/Macau', 'Asia/Magadan', 'Asia/Makassar', 'Asia/Manila', 'Asia/Muscat', 'Asia/Nicosia', 'Asia/Novokuznetsk', 'Asia/Novosibirsk', 'Asia/Omsk', 'Asia/Oral', 'Asia/Phnom_Penh', 'Asia/Pontianak', 'Asia/Pyongyang', 'Asia/Qatar', 'Asia/Qostanay', 'Asia/Qyzylorda', 'Asia/Riyadh', 'Asia/Sakhalin', 'Asia/Samarkand', 'Asia/Seoul', 'Asia/Shanghai', 'Asia/Singapore', 'Asia/Srednekolymsk', 'Asia/Taipei', 'Asia/Tashkent', 'Asia/Tbilisi', 'Asia/Tehran', 'Asia/Thimphu', 'Asia/Tokyo', 'Asia/Tomsk', 'Asia/Ulaanbaatar', 'Asia/Urumqi', 'Asia/Ust-Nera', 'Asia/Vientiane', 'Asia/Vladivostok', 'Asia/Yakutsk', 'Asia/Yangon', 'Asia/Yekaterinburg', 'Asia/Yerevan', 'Atlantic/Azores', 'Atlantic/Bermuda', 'Atlantic/Canary', 'Atlantic/Cape_Verde', 'Atlantic/Faroe', 'Atlantic/Madeira', 'Atlantic/Reykjavik', 'Atlantic/South_Georgia', 'Atlantic/St_Helena', 'Atlantic/Stanley', 'Australia/Adelaide', 'Australia/Brisbane', 'Australia/Broken_Hill', 'Australia/Darwin', 'Australia/Eucla', 'Australia/Hobart', 'Australia/Lindeman', 'Australia/Lord_Howe', 'Australia/Melbourne', 'Australia/Perth', 'Australia/Sydney', 'Canada/Atlantic', 'Canada/Central', 'Canada/Eastern', 'Canada/Mountain', 'Canada/Newfoundland', 'Canada/Pacific', 'Europe/Amsterdam', 'Europe/Andorra', 'Europe/Astrakhan', 'Europe/Athens', 'Europe/Belgrade', 'Europe/Berlin', 'Europe/Bratislava', 'Europe/Brussels', 'Europe/Bucharest', 'Europe/Budapest', 'Europe/Busingen', 'Europe/Chisinau', 'Europe/Copenhagen', 'Europe/Dublin', 'Europe/Gibraltar', 'Europe/Guernsey', 'Europe/Helsinki', 'Europe/Isle_of_Man', 'Europe/Istanbul', 'Europe/Jersey', 'Europe/Kaliningrad', 'Europe/Kirov', 'Europe/Kyiv', 'Europe/Lisbon', 'Europe/Ljubljana', 'Europe/London', 'Europe/Luxembourg', 'Europe/Madrid', 'Europe/Malta', 'Europe/Mariehamn', 'Europe/Minsk', 'Europe/Monaco', 'Europe/Moscow', 'Europe/Oslo', 'Europe/Paris', 'Europe/Podgorica', 'Europe/Prague', 'Europe/Riga', 'Europe/Rome', 'Europe/Samara', 'Europe/San_Marino', 'Europe/Sarajevo', 'Europe/Saratov', 'Europe/Simferopol', 'Europe/Skopje', 'Europe/Sofia', 'Europe/Stockholm', 'Europe/Tallinn', 'Europe/Tirane', 'Europe/Ulyanovsk', 'Europe/Vaduz', 'Europe/Vatican', 'Europe/Vienna', 'Europe/Vilnius', 'Europe/Volgograd', 'Europe/Warsaw', 'Europe/Zagreb', 'Europe/Zurich', 'GMT', 'Indian/Antananarivo', 'Indian/Chagos', 'Indian/Christmas', 'Indian/Cocos', 'Indian/Comoro', 'Indian/Kerguelen', 'Indian/Mahe', 'Indian/Maldives', 'Indian/Mauritius', 'Indian/Mayotte', 'Indian/Reunion', 'Pacific/Apia', 'Pacific/Auckland', 'Pacific/Bougainville', 'Pacific/Chatham', 'Pacific/Chuuk', 'Pacific/Easter', 'Pacific/Efate', 'Pacific/Fakaofo', 'Pacific/Fiji', 'Pacific/Funafuti', 'Pacific/Galapagos', 'Pacific/Gambier', 'Pacific/Guadalcanal', 'Pacific/Guam', 'Pacific/Honolulu', 'Pacific/Kanton', 'Pacific/Kiritimati', 'Pacific/Kosrae', 'Pacific/Kwajalein', 'Pacific/Majuro', 'Pacific/Marquesas', 'Pacific/Midway', 'Pacific/Nauru', 'Pacific/Niue', 'Pacific/Norfolk', 'Pacific/Noumea', 'Pacific/Pago_Pago', 'Pacific/Palau', 'Pacific/Pitcairn', 'Pacific/Pohnpei', 'Pacific/Port_Moresby', 'Pacific/Rarotonga', 'Pacific/Saipan', 'Pacific/Tahiti', 'Pacific/Tarawa', 'Pacific/Tongatapu', 'Pacific/Wake', 'Pacific/Wallis', 'US/Alaska', 'US/Arizona', 'US/Central', 'US/Eastern', 'US/Hawaii', 'US/Mountain', 'US/Pacific', 'UTC']

In [52]:
# 时区表式
ts = ts.tz_localize(tz = 'UTC')
ts

2030-03-01 00:00:00+00:00   -1.565496
2030-03-02 00:00:00+00:00   -0.526696
2030-03-03 00:00:00+00:00    1.001550
Freq: D, dtype: float64

In [53]:
# 时区转换
ts.tz_convert('Asia/Shanghai')

2030-03-01 08:00:00+08:00   -1.565496
2030-03-02 08:00:00+08:00   -0.526696
2030-03-03 08:00:00+08:00    1.001550
Freq: D, dtype: float64