### 美国各州人口数据分析
首先导入文件，并查看数据样本

In [42]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#### 加载数据
- state-abbrevs.csv
- state-areas.CsV
- state-population.csv

In [43]:
abb = pd.read_csv('./data/12_美国人口数据分析项目/state-abbrevs.csv')
areas = pd.read_csv('./data/12_美国人口数据分析项目/state-areas.csv')
pop = pd.read_csv('./data/12_美国人口数据分析项目/state-population.csv')

In [44]:
display(areas.head(), areas.shape)
display(abb.head(), abb.shape)
display(pop.head(), pop.shape)

        state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

(52, 2)

        state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

(51, 2)

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

(2544, 4)

合并population与abbrevs两个DataFrame
- 分别依据state/region列和abbreviation列来合并。
- 为了保留所有信息，使用外合并。merge()

In [45]:
pop_abb = pop.merge(abb, how='outer', left_on='state/region', right_on='abbreviation')
pop_abb.head()

  state/region     ages  year  population   state abbreviation
0           AK    total  1990    553290.0  Alaska           AK
1           AK  under18  1990    177502.0  Alaska           AK
2           AK    total  1992    588736.0  Alaska           AK
3           AK  under18  1991    182180.0  Alaska           AK
4           AK  under18  1992    184878.0  Alaska           AK

去除abbreviation的那一列(axis=1)

In [46]:
pop_abb.drop(columns='abbreviation', inplace=True, axis=1)
pop_abb.head()

  state/region     ages  year  population   state
0           AK    total  1990    553290.0  Alaska
1           AK  under18  1990    177502.0  Alaska
2           AK    total  1992    588736.0  Alaska
3           AK  under18  1991    182180.0  Alaska
4           AK  under18  1992    184878.0  Alaska

查看存在缺失数据的列。
- 使用pop_abb.isnull().any()

In [48]:
pop_abb.isnull().any()

state/region    False
ages            False
year            False
population       True
state            True
dtype: bool

查看缺失数据
- 根据数据是否缺失情况显示数据，如果缺失为True，那么显示

In [51]:
# 存在空值的行
cond = pop_abb.isnull().any(axis=1)
cond

# 查看缺失数据
pop_abb.loc[cond]

     state/region     ages  year   population state
1872           PR  under18  1990          NaN   NaN
1873           PR    total  1990          NaN   NaN
1874           PR    total  1991          NaN   NaN
1875           PR  under18  1991          NaN   NaN
1876           PR    total  1993          NaN   NaN
...           ...      ...   ...          ...   ...
2203          USA    total  2010  309326295.0   NaN
2204          USA  under18  2011   73902222.0   NaN
2205          USA    total  2011  311582564.0   NaN
2206          USA  under18  2012   73708179.0   NaN
2207          USA    total  2012  313873685.0   NaN

[96 rows x 5 columns]

找到有哪些state/region使得state的值为NaN
- 使用unique()查看非重复值

In [57]:
cond2 = pop_abb['state'].isnull()
cond2

pop_abb.loc[cond2]['state/region'].unique()

array(['PR', 'USA'], dtype=object)

填充state这一列的所有NaN
- 找到的这些state/region的state项补上正确的值

> PR => Puerto Rico    
> USA => United State

In [58]:
cond = pop_abb['state/region'] == 'PR'
cond

pop_abb['state'][cond] = 'Puerto Rico'

C:\Users\Administrator\AppData\Local\Temp\ipykernel_30732\1286741494.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pop_abb['state'][cond] = 'Puerto Rico'

In [59]:
pop_abb[cond]

     state/region     ages  year  population        state
1872           PR  under18  1990         NaN  Puerto Rico
1873           PR    total  1990         NaN  Puerto Rico
1874           PR    total  1991         NaN  Puerto Rico
1875           PR  under18  1991         NaN  Puerto Rico
1876           PR    total  1993         NaN  Puerto Rico
1877           PR  under18  1993         NaN  Puerto Rico
1878           PR  under18  1992         NaN  Puerto Rico
1879           PR    total  1992         NaN  Puerto Rico
1880           PR  under18  1994         NaN  Puerto Rico
1881           PR    total  1994         NaN  Puerto Rico
1882           PR    total  1995         NaN  Puerto Rico
1883           PR  under18  1995         NaN  Puerto Rico
1884           PR  under18  1996         NaN  Puerto Rico
1885           PR    total  1996         NaN  Puerto Rico
1886           PR  under18  1998         NaN  Puerto Rico
1887           PR    total  1998         NaN  Puerto Rico
1888           PR    total  1997         NaN  Puerto Rico
1889           PR  under18  1997         NaN  Puerto Rico
1890           PR    total  1999         NaN  Puerto Rico
1891           PR  under18  1999         NaN  Puerto Rico
1892           PR    total  2000   3810605.0  Puerto Rico
1893           PR  under18  2000   1089063.0  Puerto Rico
1894           PR    total  2001   3818774.0  Puerto Rico
1895           PR  under18  2001   1077566.0  Puerto Rico
1896           PR    total  2002   3823701.0  Puerto Rico
1897           PR  under18  2002   1065051.0  Puerto Rico
1898           PR    total  2004   3826878.0  Puerto Rico
1899           PR  under18  2004   1035919.0  Puerto Rico
1900           PR    total  2003   3826095.0  Puerto Rico
1901           PR  under18  2003   1050615.0  Puerto Rico
1902           PR    total  2005   3821362.0  Puerto Rico
1903           PR  under18  2005   1019447.0  Puerto Rico
1904           PR    total  2006   3805214.0  Puerto Rico
1905           PR  under18  2006    998543.0  Puerto Rico
1906           PR    total  2007   3782995.0  Puerto Rico
1907           PR  under18  2007    973613.0  Puerto Rico
1908           PR    total  2008   3760866.0  Puerto Rico
1909           PR  under18  2008    945705.0  Puerto Rico
1910           PR  under18  2013    814068.0  Puerto Rico
1911           PR    total  2013   3615086.0  Puerto Rico
1912           PR    total  2009   3740410.0  Puerto Rico
1913           PR  under18  2009    920794.0  Puerto Rico
1914           PR    total  2010   3721208.0  Puerto Rico
1915           PR  under18  2010    896945.0  Puerto Rico
1916           PR  under18  2011    869327.0  Puerto Rico
1917           PR    total  2011   3686580.0  Puerto Rico
1918           PR  under18  2012    841740.0  Puerto Rico
1919           PR    total  2012   3651545.0  Puerto Rico

In [60]:
cond = pop_abb['state/region'] == 'USA'
cond

pop_abb['state'][cond] = 'United State'

C:\Users\Administrator\AppData\Local\Temp\ipykernel_30732\2183590898.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pop_abb['state'][cond] = 'United State'

In [61]:
pop_abb[cond]

     state/region     ages  year   population         state
2160          USA  under18  1990   64218512.0  United State
2161          USA    total  1990  249622814.0  United State
2162          USA    total  1991  252980942.0  United State
2163          USA  under18  1991   65313018.0  United State
2164          USA  under18  1992   66509177.0  United State
2165          USA    total  1992  256514231.0  United State
2166          USA    total  1993  259918595.0  United State
2167          USA  under18  1993   67594938.0  United State
2168          USA  under18  1994   68640936.0  United State
2169          USA    total  1994  263125826.0  United State
2170          USA  under18  1995   69473140.0  United State
2171          USA  under18  1996   70233512.0  United State
2172          USA    total  1995  266278403.0  United State
2173          USA    total  1996  269394291.0  United State
2174          USA    total  1997  272646932.0  United State
2175          USA  under18  1997   70920738.0  United State
2176          USA  under18  1998   71431406.0  United State
2177          USA    total  1998  275854116.0  United State
2178          USA  under18  1999   71946051.0  United State
2179          USA    total  2000  282162411.0  United State
2180          USA  under18  2000   72376189.0  United State
2181          USA    total  1999  279040181.0  United State
2182          USA    total  2001  284968955.0  United State
2183          USA  under18  2001   72671175.0  United State
2184          USA    total  2002  287625193.0  United State
2185          USA  under18  2002   72936457.0  United State
2186          USA    total  2003  290107933.0  United State
2187          USA  under18  2003   73100758.0  United State
2188          USA    total  2004  292805298.0  United State
2189          USA  under18  2004   73297735.0  United State
2190          USA    total  2005  295516599.0  United State
2191          USA  under18  2005   73523669.0  United State
2192          USA    total  2006  298379912.0  United State
2193          USA  under18  2006   73757714.0  United State
2194          USA    total  2007  301231207.0  United State
2195          USA  under18  2007   74019405.0  United State
2196          USA    total  2008  304093966.0  United State
2197          USA  under18  2008   74104602.0  United State
2198          USA  under18  2013   73585872.0  United State
2199          USA    total  2013  316128839.0  United State
2200          USA    total  2009  306771529.0  United State
2201          USA  under18  2009   74134167.0  United State
2202          USA  under18  2010   74119556.0  United State
2203          USA    total  2010  309326295.0  United State
2204          USA  under18  2011   73902222.0  United State
2205          USA    total  2011  311582564.0  United State
2206          USA  under18  2012   73708179.0  United State
2207          USA    total  2012  313873685.0  United State

合并各州面积数据areas，使用左合并。

In [63]:
display(areas.head(3), pop_abb.head(3))

     state  area (sq. mi)
0  Alabama          52423
1   Alaska         656425
2  Arizona         114006

  state/region     ages  year  population   state
0           AK    total  1990    553290.0  Alaska
1           AK  under18  1990    177502.0  Alaska
2           AK    total  1992    588736.0  Alaska

In [65]:
pop_abb_areas = pop_abb.merge(areas, how='left')
pop_abb_areas.head()

  state/region     ages  year  population   state  area (sq. mi)
0           AK    total  1990    553290.0  Alaska       656425.0
1           AK  under18  1990    177502.0  Alaska       656425.0
2           AK    total  1992    588736.0  Alaska       656425.0
3           AK  under18  1991    182180.0  Alaska       656425.0
4           AK  under18  1992    184878.0  Alaska       656425.0

继续寻找存在缺失数据的列

In [67]:
pop_abb_areas.isnull().any()

pop_abb_areas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2544 entries, 0 to 2543
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   state/region   2544 non-null   object
 1   ages           2544 non-null   object
 2   year           2544 non-null   int64
 3   population     2524 non-null   float64
 4   state          2544 non-null   object
 5   area (sq. mi)  2496 non-null   float64
dtypes: float64(2), int64(1), object(3)
memory usage: 119.4+ KB

我们会发现area(sq.mi)这一列有缺失数昺，为了找出是哪一行，我们需要找出是哪个state没有数据

In [72]:
cond = pop_abb_areas['area (sq. mi)'].isnull()
cond

pop_abb_areas['state'][cond].unique()

array(['United State'], dtype=object)

去除含有缺失数据的行

In [75]:
cond = pop_abb_areas.notnull().all(axis=1)
cond

pop_abb_areas2 = pop_abb_areas.loc[cond]
pop_abb_areas2

     state/region     ages  year  population    state  area (sq. mi)
0              AK    total  1990    553290.0   Alaska       656425.0
1              AK  under18  1990    177502.0   Alaska       656425.0
2              AK    total  1992    588736.0   Alaska       656425.0
3              AK  under18  1991    182180.0   Alaska       656425.0
4              AK  under18  1992    184878.0   Alaska       656425.0
...           ...      ...   ...         ...      ...            ...
2539           WY  under18  1993    137458.0  Wyoming        97818.0
2540           WY    total  1991    459260.0  Wyoming        97818.0
2541           WY  under18  1991    136720.0  Wyoming        97818.0
2542           WY  under18  1990    136078.0  Wyoming        97818.0
2543           WY    total  1990    453690.0  Wyoming        97818.0

[2476 rows x 6 columns]

再查看数据是否缺失

In [78]:
pop_abb_areas2.isnull().any()

state/region     False
ages             False
year             False
population       False
state            False
area (sq. mi)    False
dtype: bool

找出2010年的全民人口数据
- df.query(查询语句)

In [82]:
df_2010 = pop_abb_areas2.query('year == 2010 and ages == "total"')
df_2010

,state/region,ages,year,population,state,area (sq. mi)
43,AK,total,2010,713868.0,Alaska,656425.0
51,AL,total,2010,4785570.0,Alabama,52423.0
141,AR,total,2010,2922280.0,Arkansas,53182.0
149,AZ,total,2010,6408790.0,Arizona,114006.0
197,CA,total,2010,37333601.0,California,163707.0
283,CO,total,2010,5048196.0,Colorado,104100.0
293,CT,total,2010,3579210.0,Connecticut,5544.0
341,DC,total,2010,605125.0,District of Columbia,68.0
427,DE,total,2010,899711.0,Delaware,1954.0
475,FL,total,2010,18846054.0,Florida,65758.0
485,GA,total,2010,9713248.0,Georgia,59441.0
570,HI,total,2010,1363731.0,Hawaii,10932.0
618,IA,total,2010,3050314.0,Iowa,56276.0
629,ID,total,2010,1570718.0,Idaho,83574.0
714,IL,total,2010,12839695.0,Illinois,57918.0
725,IN,total,2010,6489965.0,Indiana,36420.0
773,KS,total,2010,2858910.0,Kansas,82282.0
858,KY,total,2010,4347698.0,Kentucky,40411.0
869,LA,total,2010,4545392.0,Louisiana,51843.0
954,MA,total,2010,6563263.0,Massachusetts,10555.0
965,MD,total,2010,5787193.0,Maryland,12407.0
1050,ME,total,2010,1327366.0,Maine,35387.0
1061,MI,total,2010,9876149.0,Michigan,96810.0
1146,MN,total,2010,5310337.0,Minnesota,86943.0
1194,MO,total,2010,5996063.0,Missouri,69709.0
1205,MS,total,2010,2970047.0,Mississippi,48434.0
1253,MT,total,2010,990527.0,Montana,147046.0
1338,NC,total,2010,9559533.0,North Carolina,53821.0
1349,ND,total,2010,674344.0,North Dakota,70704.0
1434,NE,total,2010,1829838.0,Nebraska,77358.0
1482,NH,total,2010,1316614.0,New Hampshire,9351.0
1493,NJ,total,2010,8802707.0,New Jersey,8722.0
1578,NM,total,2010,2064982.0,New Mexico,121593.0
1589,NV,total,2010,2703230.0,Nevada,110567.0
1637,NY,total,2010,19398228.0,New York,54475.0
1722,OH,total,2010,11545435.0,Ohio,44828.0
1733,OK,total,2010,3759263.0,Oklahoma,69903.0
1818,OR,total,2010,3837208.0,Oregon,98386.0
1829,PA,total,2010,12710472.0,Pennsylvania,46058.0
1914,PR,total,2010,3721208.0,Puerto Rico,3515.0
1962,RI,total,2010,1052669.0,Rhode Island,1545.0
1973,SC,total,2010,4636361.0,South Carolina,32007.0
2058,SD,total,2010,816211.0,South Dakota,77121.0
2069,TN,total,2010,6356683.0,Tennessee,42146.0
2154,TX,total,2010,25245178.0,Texas,268601.0
2213,UT,total,2010,2774424.0,Utah,84904.0
2261,VA,total,2010,8024417.0,Virginia,42769.0
2346,VT,total,2010,625793.0,Vermont,9615.0
2394,WA,total,2010,6742256.0,Washington,71303.0
2442,WI,total,2010,5689060.0,Wisconsin,65503.0
2453,WV,total,2010,1854146.0,West Virginia,24231.0
2501,WY,total,2010,564222.0,Wyoming,97818.0

以state列作为新的行索引
- 使用set index

In [83]:
df_2010.set_index('state', inplace=True)
df_2010

                     state/region   ages  year  population  area (sq. mi)
state
Alaska                         AK  total  2010    713868.0       656425.0
Alabama                        AL  total  2010   4785570.0        52423.0
Arkansas                       AR  total  2010   2922280.0        53182.0
Arizona                        AZ  total  2010   6408790.0       114006.0
California                     CA  total  2010  37333601.0       163707.0
Colorado                       CO  total  2010   5048196.0       104100.0
Connecticut                    CT  total  2010   3579210.0         5544.0
District of Columbia           DC  total  2010    605125.0           68.0
Delaware                       DE  total  2010    899711.0         1954.0
Florida                        FL  total  2010  18846054.0        65758.0
Georgia                        GA  total  2010   9713248.0        59441.0
Hawaii                         HI  total  2010   1363731.0        10932.0
Iowa                           IA  total  2010   3050314.0        56276.0
Idaho                          ID  total  2010   1570718.0        83574.0
Illinois                       IL  total  2010  12839695.0        57918.0
Indiana                        IN  total  2010   6489965.0        36420.0
Kansas                         KS  total  2010   2858910.0        82282.0
Kentucky                       KY  total  2010   4347698.0        40411.0
Louisiana                      LA  total  2010   4545392.0        51843.0
Massachusetts                  MA  total  2010   6563263.0        10555.0
Maryland                       MD  total  2010   5787193.0        12407.0
Maine                          ME  total  2010   1327366.0        35387.0
Michigan                       MI  total  2010   9876149.0        96810.0
Minnesota                      MN  total  2010   5310337.0        86943.0
Missouri                       MO  total  2010   5996063.0        69709.0
Mississippi                    MS  total  2010   2970047.0        48434.0
Montana                        MT  total  2010    990527.0       147046.0
North Carolina                 NC  total  2010   9559533.0        53821.0
North Dakota                   ND  total  2010    674344.0        70704.0
Nebraska                       NE  total  2010   1829838.0        77358.0
New Hampshire                  NH  total  2010   1316614.0         9351.0
New Jersey                     NJ  total  2010   8802707.0         8722.0
New Mexico                     NM  total  2010   2064982.0       121593.0
Nevada                         NV  total  2010   2703230.0       110567.0
New York                       NY  total  2010  19398228.0        54475.0
Ohio                           OH  total  2010  11545435.0        44828.0
Oklahoma                       OK  total  2010   3759263.0        69903.0
Oregon                         OR  total  2010   3837208.0        98386.0
Pennsylvania                   PA  total  2010  12710472.0        46058.0
Puerto Rico                    PR  total  2010   3721208.0         3515.0
Rhode Island                   RI  total  2010   1052669.0         1545.0
South Carolina                 SC  total  2010   4636361.0        32007.0
South Dakota                   SD  total  2010    816211.0        77121.0
Tennessee                      TN  total  2010   6356683.0        42146.0
Texas                          TX  total  2010  25245178.0       268601.0
Utah                           UT  total  2010   2774424.0        84904.0
Virginia                       VA  total  2010   8024417.0        42769.0
Vermont                        VT  total  2010    625793.0         9615.0
Washington                     WA  total  2010   6742256.0        71303.0
Wisconsin                      WI  total  2010   5689060.0        65503.0
West Virginia                  WV  total  2010   1854146.0        24231.0
Wyoming                        WY  total  2010    564222.0        97818.0

计算人口密度density

In [84]:
df_2010.head()

           state/region   ages  year  population  area (sq. mi)
state
Alaska               AK  total  2010    713868.0       656425.0
Alabama              AL  total  2010   4785570.0        52423.0
Arkansas             AR  total  2010   2922280.0        53182.0
Arizona              AZ  total  2010   6408790.0       114006.0
California           CA  total  2010  37333601.0       163707.0

In [86]:
# 人口密度
df_2010['density'] = df_2010['population'] / df_2010['area (sq. mi)']
df_2010.head()

C:\Users\Administrator\AppData\Local\Temp\ipykernel_30732\2689996360.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2010['density'] = df_2010['population'] / df_2010['area (sq. mi)']

           state/region   ages  year  population  area (sq. mi)     density
state
Alaska               AK  total  2010    713868.0       656425.0    1.087509
Alabama              AL  total  2010   4785570.0        52423.0   91.287603
Arkansas             AR  total  2010   2922280.0        53182.0   54.948667
Arizona              AZ  total  2010   6408790.0       114006.0   56.214497
California           CA  total  2010  37333601.0       163707.0  228.051342

排序，并找出人口密度最高的五个州sort values

In [87]:
df_2010.sort_values(by='density', ascending=False).head()

,state/region,ages,year,population,area (sq. mi),density
state,,,,,,
District of Columbia,DC,total,2010,605125.0,68.0,8898.897059
Puerto Rico,PR,total,2010,3721208.0,3515.0,1058.665149
New Jersey,NJ,total,2010,8802707.0,8722.0,1009.253268
Rhode Island,RI,total,2010,1052669.0,1545.0,681.339159
Connecticut,CT,total,2010,3579210.0,5544.0,645.600649

排序，找出人口密度最低的五个州

In [88]:
df_2010.sort_values(by='density').head()

             state/region   ages  year  population  area (sq. mi)    density
state
Alaska                 AK  total  2010    713868.0       656425.0   1.087509
Wyoming                WY  total  2010    564222.0        97818.0   5.768079
Montana                MT  total  2010    990527.0       147046.0   6.736171
North Dakota           ND  total  2010    674344.0        70704.0   9.537565
South Dakota           SD  total  2010    816211.0        77121.0  10.583512