# Pandas数据排序
# 一、Series的排序
**Series的排序**
Series.sort_values(ascending = True, inplace = False)
**DataFrame**
DataFrame.sort_values(by, ascending = True, inplace = False)
- by:字符串或者List[string]

In [1]:
import pandas as pd
file_path = r"D:\JupyterProject\study-pandas\file\datas\weather_20230115134249.csv"
df = pd.read_csv(file_path)
df.head()

           日期   城市  行政区  观测站  气温(度)  相对湿度(%)  累积雨量(mm)
0  2015-01-01  新北市  烏來區   福山  13.7℃       92       0.0
1  2015-01-02  臺南市  安平區   安平  23.5℃       70       0.0
2  2015-01-03  臺東縣  東河鄉  七塊厝  19.6℃       86       0.0
3  2015-01-04  新北市  貢寮區   福隆  14.2℃       96     -99.0
4  2015-01-05  南投縣  仁愛鄉  小奇萊   8.3℃       57       0.0

In [3]:
sorted_series = df["相对湿度(%)"].sort_values()

In [4]:
print(sorted_series)

381   -9900
162   -9900
453   -9900
470   -9900
24    -9900
       ...
167     100
274     100
95      100
49      100
352     100
Name: 相对湿度(%), Length: 484, dtype: int64

In [5]:
df.sort_values(by = ["相对湿度(%)"])
print(df)

             日期   城市  行政区  观测站  气温(度)  相对湿度(%)  累积雨量(mm)
0    2015-01-01  新北市  烏來區   福山  13.7℃       92       0.0
1    2015-01-02  臺南市  安平區   安平  23.5℃       70       0.0
2    2015-01-03  臺東縣  東河鄉  七塊厝  19.6℃       86       0.0
3    2015-01-04  新北市  貢寮區   福隆  14.2℃       96     -99.0
4    2015-01-05  南投縣  仁愛鄉  小奇萊   8.3℃       57       0.0
..          ...  ...  ...  ...    ...      ...       ...
479  2016-04-24  新北市  板橋區   板橋  15.6℃       73       5.0
480  2016-04-25  宜蘭縣  大同鄉  翠峰湖   7.8℃      100       0.0
481  2016-04-26  花蓮縣  壽豐鄉   大坑  15.7℃       94       0.0
482  2016-04-27  新竹縣  五峰鄉   雪霸  15.7℃       62       0.0
483  2016-04-28  桃園市  大溪區   大溪  14.8℃       77       8.0

[484 rows x 7 columns]

In [6]:
df.sort_values(by = ["相对湿度(%)"], inplace = True)
print(df)

             日期   城市  行政区   观测站  气温(度)  相对湿度(%)  累积雨量(mm)
381  2016-01-17  高雄市  梓官區    梓官   -99℃    -9900     -99.0
162  2015-06-12  臺中市  烏日區    烏日   -99℃    -9900     -99.0
453  2016-03-29  屏東縣  長治鄉    長治   -99℃    -9900       0.0
470  2016-04-15  新北市  永和區    永和   -99℃    -9900     -99.0
24   2015-01-25  臺中市  西屯區    西屯   -99℃    -9900     -99.0
..          ...  ...  ...   ...    ...      ...       ...
167  2015-06-17  彰化縣  芳苑鄉    芳苑  19.5℃      100       0.0
274  2015-10-02  基隆市  中正區   基隆嶼  12.8℃      100       7.5
95   2015-04-06  臺東縣  達仁鄉   勝林山  15.9℃      100       0.0
49   2015-02-19  宜蘭縣  南澳鄉   西德山   9.1℃      100       4.5
352  2015-12-19  花蓮縣  卓溪鄉  瑞穗林道  12.5℃      100       4.0

[484 rows x 7 columns]

# 二、Pandas字符串处理
## 2.1 Pandas字符串处理
1. 使用方法：先获取Series的str属性，然后在属性上调用函数
2. 只能用于字符串
3. DataFrame没有
4. 链接：https://pandas.pydata.org/pandas-docs/stable/reference/series.html#string-handling
## 2.2 应用
### 2.2.1 获取Series的str属性，然后使用各种字符串处理函数
- 字符串替换replace:返回一个替换后的Series
- startswith
- slice方法
- 正则表达式

In [7]:

import pandas as pd
file_path = r"D:\JupyterProject\study-pandas\file\datas\weather_20230115134249.csv"
df = pd.read_csv(file_path)
df.head()

           日期   城市  行政区  观测站  气温(度)  相对湿度(%)  累积雨量(mm)
0  2015-01-01  新北市  烏來區   福山  13.7℃       92       0.0
1  2015-01-02  臺南市  安平區   安平  23.5℃       70       0.0
2  2015-01-03  臺東縣  東河鄉  七塊厝  19.6℃       86       0.0
3  2015-01-04  新北市  貢寮區   福隆  14.2℃       96     -99.0
4  2015-01-05  南投縣  仁愛鄉  小奇萊   8.3℃       57       0.0

In [8]:
#字符串替换
df["气温(度)"].str.replace("℃", "")

0      13.7
1      23.5
2      19.6
3      14.2
4       8.3
       ...
479    15.6
480     7.8
481    15.7
482    15.7
483    14.8
Name: 气温(度), Length: 484, dtype: object

In [12]:
condition = df["日期"].str.startswith("2015-03")
condition

0      False
1      False
2      False
3      False
4      False
       ...
479    False
480    False
481    False
482    False
483    False
Name: 日期, Length: 484, dtype: bool

In [13]:
df[condition].head()

            日期   城市  行政区  观测站  气温(度)  相对湿度(%)  累积雨量(mm)
59  2015-03-01  臺北市  士林區  科教館  16.8℃       67       3.5
60  2015-03-02  桃園市  大園區   竹圍  13.5℃       95       0.0
61  2015-03-03  南投縣  草屯鎮   草屯  23.7℃       57       0.0
62  2015-03-04  宜蘭縣  壯圍鄉   壯圍  16.3℃       79       0.0
63  2015-03-05  彰化縣  伸港鄉  防潮門  17.1℃       80       0.0

In [14]:
#slice 比如获取日期的月份
df["日期"].str.slice(5, 7)

0      01
1      01
2      01
3      01
4      01
       ..
479    04
480    04
481    04
482    04
483    04
Name: 日期, Length: 484, dtype: object

In [19]:
def get_col(x):
    year, month, day = x["日期"].split('-')
    return f"{year}年{month}月{day}日"
df.loc[:, "中文日期"] = df.apply(get_col, axis = 1)
print(df)

             日期   城市  行政区  观测站  气温(度)  相对湿度(%)  累积雨量(mm)         中文日期
0    2015-01-01  新北市  烏來區   福山  13.7℃       92       0.0  2015年01月01日
1    2015-01-02  臺南市  安平區   安平  23.5℃       70       0.0  2015年01月02日
2    2015-01-03  臺東縣  東河鄉  七塊厝  19.6℃       86       0.0  2015年01月03日
3    2015-01-04  新北市  貢寮區   福隆  14.2℃       96     -99.0  2015年01月04日
4    2015-01-05  南投縣  仁愛鄉  小奇萊   8.3℃       57       0.0  2015年01月05日
..          ...  ...  ...  ...    ...      ...       ...          ...
479  2016-04-24  新北市  板橋區   板橋  15.6℃       73       5.0  2016年04月24日
480  2016-04-25  宜蘭縣  大同鄉  翠峰湖   7.8℃      100       0.0  2016年04月25日
481  2016-04-26  花蓮縣  壽豐鄉   大坑  15.7℃       94       0.0  2016年04月26日
482  2016-04-27  新竹縣  五峰鄉   雪霸  15.7℃       62       0.0  2016年04月27日
483  2016-04-28  桃園市  大溪區   大溪  14.8℃       77       8.0  2016年04月28日

[484 rows x 8 columns]

# 三、axis参数如何理解？
- axis = 0:当操作是单行操作 那么指的是操作某一行；如果操作是聚合操作，那么指的是跨行操作。axis为1时同理。

In [24]:
import pandas as pd
import numpy as np

df = pd.DataFrame(
    np.arange(12).reshape(3, 4), 
    columns = ['A', 'B', 'C', 'D']
)
df

   A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [28]:
#删除A这一列 单列操作 所以axis=1
new_df = df.drop('A', axis = 1)
print(new_df)

   B   C   D
0  1   2   3
1  5   6   7
2  9  10  11

In [29]:
#mean聚合操作 计算每一列 即跨行 因而axis=0
df.mean(axis = 0)

A    4.0
B    5.0
C    6.0
D    7.0
dtype: float64